baseURL = 'https://caalden.github.io/film/'
languageCode = 'en-us'
title = 'CaAlden: Films'
copyright = 'Â© 2025 Campbell Alden, All rights reserved.'
[taxonomies]
  genre = 'genres'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
